### ISSUE TITLE
Add support for styled components

### ISSUE THREAD

**Issue by mskelton** [dzhavat/css-to-mdn#2]
The docs link doesn't work for styles in styled components.  I'm using the [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) extensions.  My guess is this might work better by targeting a scope rather than a set of file extensions?

![2019-08-19_18-50-57](https://user-images.githubusercontent.com/25914066/63306965-4c34b280-c2b2-11e9-9a5b-1980ba9d360b.png)

**Comment by dzhavat** [comment]
Yeah, unfortunately the extension only works with CSS files. And it's my second one, so I've kept the things simple in order to get feedback and nice suggestions for improvements like yours :)

Anyway, maybe targeting a scope can also help me add support for `style` attribute inside an HTML files. I haven't tried using scope before. Do you know where I can read more about it?

**Comment by markypython** [comment]
Unfortunately, I don't know about how to work with scopes for an extension like this.  And it is possible that it isn't feasible, but it seems like VS Code should support it.

**Comment by dzhavat** [comment]
Thanks. Well, I'll at least give it a try. Or maybe someone can help me on SO.
